apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
data:
  config.yml: |-
    global:
      resolve_timeout: 1m
      slack_api_url: "https://hooks.slack.com/services/T02AHPP5U82/B04TLDGCF4L/7ZeZzGqct9yf3vGILhlvZf"
 
    route:
      receiver: "slack-notifications"

    receivers:
      - name: "slack-notifications"
        slack_configs:
        - channel: "#prom-alerts-slack"
          send_resolved: true
