apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: KubernetesPodNotHealthy
        expr: min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed|ErrImagePull"})[15m:1m]) > 0
        for: 1m
        annotations:
           summary: Kubernetes Pod not healthy (instance {{ $labels.instance }})
           description: "Pod has been in a non-ready state for longer than 15 minutes.\n"
      - alert: HighUsage
        expr: avg(irate(node_cpu_seconds_total{mode="idle"}[1m]) * 100) < 20
        for: 1m
        annotations:
          summary: "High usage on {{ $labels.instance }}"
          description: "{{ $labels.instance }} has a average CPU idle (current value: {{ $value }}s)"
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    rule_files:
      - /etc/prometheus/prometheus.rules
    alerting:
      alertmanagers:
      - scheme: http
        static_configs:
        - targets: ['alertmanager-service.default.svc.cluster.local:9093']

    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
      - job_name: 'node-exporter'
        static_configs:
          - targets: ['node-exporter.default.svc.cluster.local:9100']
